### ISSUE TITLE
Create a todo app

### ISSUE THREAD

**Issue by surfmuggle** [surfmuggle/Cubert#35]
Please create a basic todo app

 - user can enter todos
 - each todo has three states open, in-progress, done
 - user can change the state of a todo
 - the styling of a todo must depend on the status

**Comment by surfmuggle** [comment]
My latest [commit in the mdn branch](https://github.com/surfmuggle/TodoDrag/commits/mdn) can do this

Please create a basic todo app

- [ ]  user can enter todos
- [ ]  each todo has three states open, in-progress, done
- [ ]  user can change the state of a todo
- [ ]  the styling of a todo must depend on the status
- [ ]  a todo item must be draggable (drag and drop)
- [ ]  a drop of a todo item changes its state depending of the drop target

**Comment by surfmuggle** [comment]
Spoiler and some hints

- [ ] user can enter todos
- [ ] each todo has three states open, in-progress, done
- [ ] user can change the state of a todo
- [ ] the styling of a todo must depend on the status
- [ ] a todo item must be draggable (drag and drop)
- [ ] a drop of a todo item changes its state depending of the drop target

![image](https://user-images.githubusercontent.com/1271555/112480248-1f8e2a00-8d76-11eb-854c-98cfb0b192c8.png)

**Comment by surfmuggle** [comment]
Update


- [x] user can enter todos
- [x] each todo has three states open, in-progress, done
- [ ] user can change the state of a todo
- [x] the styling of a todo must depend on the status
- [x] a todo item must be draggable (drag and drop)
- [x] a drop of a todo item changes its state depending of the drop target
